### PR TITLE
remove useless padding, and move sizedbox

### PR DESCRIPTION
**Pull request by TheScottishFly**

### CODE REVIEW

**Review by tarkesh2shar — COMMENTED** [review]
Awesome Job

**Comment by niklasbartsch** [comment]
Please merge it for us 😁

**Review by jhoward321 — APPROVED** [review]

**Comment by zgauhar** [comment]
Is this merged yet? I am still seeing the overflow in the widget. Also the version on pub.dev is 0.1.1 while in the source is 0.1.1+3. When can i expect a merge please?

**Review by Bernardi23 — COMMENTED** [review]
When I tried this the whole search container was fully expanded. I found a solution that worked for me and I'm trying to make sure it works just right. Should be updated tomorrow.

**Comment by Bernardi23** [comment]
I'll be closing this PR since I'm going with another soltution. If the problem persists, I'll be open to suggestions again! Thanks for the contribution.

**Pull request closed without merging**
